# Required metadata
sonar.projectKey=notifications-service
sonar.projectName=Notifications Service
sonar.projectVersion=1.0

# Path to the directories containing source code
sonar.sources=src

# Encoding of the source code
sonar.sourceEncoding=UTF-8